name: Build
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    name: ${{ matrix.container || matrix.os }}/${{ matrix.packaging }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - { os: "ubuntu-latest", packaging: "apt", container: "debian:buster", python: "python3" }
          # - { os: "ubuntu-latest", packaging: "apt", container: "debian:bullseye", python: "python3" }
          # - { os: "ubuntu-latest", packaging: "apt", container: "ubuntu:focal", python: "python3" }
          # - { os: "ubuntu-latest", packaging: "apt", container: "ubuntu:jammy", python: "python3", cmake_options: "-DCMAKE_CXX_STANDARD=17" }
          # - { os: "macos-latest", packaging: "conda", python: "python" }
          - { os: "windows-latest", packaging: "conda", python: "python" }
    env:
      WORKSPACE: "${{ github.workspace }}"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Provision (Debian, Ubuntu)
        # Install Python and Git. macOS and Windows workers already have this,
        # however for Linux we are running in minimal containers.
        run: |
          apt-get update
          apt-get install -y git python3
        if: ${{ contains(matrix.container, 'debian') || contains(matrix.container, 'ubuntu') }}
      
      - name: Provision (Windows)
        run: echo "PATH=/c/Miniconda/condabin:${PATH}" >> $GITHUB_ENV
        if: ${{ contains(matrix.os, 'windows') }}
      
      - name: Debug (Windows)
        run: |
          ls /c/
      
      - name: Provision (Conda)
        # Initialize the Conda environment by default
        run: conda init --all
        if: ${{ contains(matrix.packaging, 'conda') }}
      
      - name: Checkout latest revision
        # Only the latest revision is required, as later steps do not depend on
        # tags.
        run: |
          git config --global init.defaultBranch master
          git config --global --add safe.directory '*'
          git init .
          git remote add origin ${{ github.server_url }}/${{ github.repository }}
          git fetch origin --depth=1 ${{ github.ref }}
          git checkout ${{ github.ref_name }}
      
      - name: Set-up (${{ matrix.packaging }})
        run: ${{ matrix.python }} .ci/build/${{ matrix.packaging }}.py
      
      - name: Build
        run: ${{ matrix.python }} ./.ci/build/build.py ${{ matrix.cmake_options }}
      
      - name: Run tests
        run: ${{ matrix.python }} ./.ci/build/post_build.py
